#!/usr/bin/env python3
"""Ralph Loop Daily Scan

Creates a daily report under context/ops/reports/ralph_loop_daily/REPORT_YYYY-MM-DD.md
(and legacy ops/reports for compatibility if present), and records a small sync state
snapshot so the loop can be checked for actual liveness instead of format-only output.

This is a reconstruction script: minimal, deterministic, local-only.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import subprocess
from datetime import datetime, timezone
from zoneinfo import ZoneInfo

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SYNC_STATE_PATH = os.path.join(ROOT, "context/state/ralph_loop_sync.state.json")
ITEM_GLOBS = [
    os.path.join(ROOT, "context/ops/items/*.md"),
    os.path.join(ROOT, "ops/items/*.md"),
]


def run(cmd: list[str]) -> str:
    out = subprocess.check_output(cmd, text=True)
    return out.strip()


def collect_task_counts() -> dict:
    counts: dict[str, int] = {}
    seen: set[str] = set()
    for pattern in ITEM_GLOBS:
        for path in glob.glob(pattern):
            real = os.path.realpath(path)
            if real in seen or not os.path.isfile(real):
                continue
            seen.add(real)
            status = "missing"
            try:
                with open(real, "r", encoding="utf-8") as f:
                    for line in f:
                        if line.lower().startswith("status:"):
                            status = line.split(":", 1)[1].strip().lower()
                            break
            except Exception:
                status = "read-error"
            counts[status] = counts.get(status, 0) + 1

    total = sum(counts.values())
    done = counts.get("done", 0)
    in_progress = counts.get("in-progress", 0)
    todo = counts.get("todo", 0) + counts.get("open", 0) + counts.get("backlog", 0)
    return {
        "total": total,
        "done": done,
        "in_progress": in_progress,
        "todo_like": todo,
        "by_status": counts,
        "paths_scanned": len(seen),
    }


def update_sync_state(*, started_at: str, finished_at: str, report_path: str, wip_line: str, task_counts: dict) -> None:
    state = {
        "schema_version": "state.ralph_loop_sync.v0_2",
        "created_at": started_at,
        "updated_at": finished_at,
        "notes": "auto-generated by ralph_loop_daily_scan.py",
        "last_run": {
            "started_at": started_at,
            "finished_at": finished_at,
            "status": "ok",
            "error": None,
            "report_path": report_path,
            "wip_summary": wip_line,
            "task_counts": task_counts,
        },
        "cursor": None,
        "checksums": {},
    }

    if os.path.exists(SYNC_STATE_PATH):
        try:
            with open(SYNC_STATE_PATH, "r", encoding="utf-8") as f:
                prev = json.load(f)
            state["created_at"] = prev.get("created_at", started_at)
            state["cursor"] = prev.get("cursor")
            state["checksums"] = prev.get("checksums", {})
        except Exception:
            pass

    os.makedirs(os.path.dirname(SYNC_STATE_PATH), exist_ok=True)
    with open(SYNC_STATE_PATH, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2)
        f.write("\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", default=None, help="YYYY-MM-DD (defaults to today Asia/Seoul)")
    ap.add_argument("--force", action="store_true", help="overwrite existing report file")
    ap.add_argument("--wip-limit", type=int, default=5)
    ap.add_argument("--sla-h", type=int, default=24)
    args = ap.parse_args()

    d = args.date
    if not d:
        d = datetime.now(ZoneInfo("Asia/Seoul")).strftime("%Y-%m-%d")

    # Prefer SSOT path under context/, but keep legacy ops/ path if it exists.
    report_dir = os.path.join(ROOT, "context/ops/reports/ralph_loop_daily")
    legacy_dir = os.path.join(ROOT, "ops/reports/ralph_loop_daily")
    os.makedirs(report_dir, exist_ok=True)
    if os.path.isdir(os.path.join(ROOT, "ops/reports")):
        os.makedirs(legacy_dir, exist_ok=True)

    started_at = datetime.now(timezone.utc).isoformat()
    wip_line = run(["python3", os.path.join(ROOT, "scripts/ralph_loop_wip_sweep.py"), "--limit", str(args.wip_limit), "--sla-h", str(args.sla_h)])
    task_counts = collect_task_counts()

    report_path = os.path.join(report_dir, f"REPORT_{d}.md")
    legacy_report_path = os.path.join(legacy_dir, f"REPORT_{d}.md")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    status_lines = "\n".join(f"- {k}: {v}" for k, v in sorted(task_counts["by_status"].items())) or "- (none)"

    content = f"""# Ralph Loop Daily Scan — {d}

Generated: {now}

## Summary
- {wip_line}
- TASK_COUNTS total={task_counts['total']} done={task_counts['done']} in_progress={task_counts['in_progress']} todo_like={task_counts['todo_like']}

## Task Counts
- Total tasks scanned: {task_counts['total']}
- Done: {task_counts['done']}
- In progress: {task_counts['in_progress']}
- Todo-like: {task_counts['todo_like']}
- Files scanned: {task_counts['paths_scanned']}

### Counts by status
{status_lines}

## WIP Sweep
- (See summary line; reconstructed runner)

## Cron Health
- Reconstructed environment: cron DB may be missing; see `context/RALPH_LOOP_CRON_ID_REMAP_TABLE_2026-03-06.md`.

## State Integrity / Drift
- Executed via `python3 scripts/ralph_loop_drift_check.py` (baseline + drift report; auto-repair may be enabled by scheduler).

## Liveness Proof
- Sync state updated: `context/state/ralph_loop_sync.state.json`
- Report path: `context/ops/reports/ralph_loop_daily/REPORT_{d}.md`

## Next Actions
- If `stale>0`, triage in-progress items: split / mark blocked / return to backlog.
- If `total` and `done` stay unchanged across multiple runs, require explicit task state transitions or fix the upstream ledger sync.
"""

    if os.path.exists(report_path) and not args.force:
        print(report_path)
        return 0

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(content)

    try:
        if os.path.isdir(legacy_dir):
            with open(legacy_report_path, "w", encoding="utf-8") as f:
                f.write(content)
    except Exception:
        pass

    finished_at = datetime.now(timezone.utc).isoformat()
    update_sync_state(
        started_at=started_at,
        finished_at=finished_at,
        report_path=os.path.relpath(report_path, ROOT),
        wip_line=wip_line,
        task_counts=task_counts,
    )

    print(report_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
